"""
Django settings for docOps project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
from pathlib import Path


# INPUT:
#   - The file Django is currently running (settings.py)
#
# PROCESS:
#   - Find the real, full location of this file on the computer
#   - Move up two folders to reach the main project directory
#

# OUTPUT:
#   - BASE_DIR now represents the project’s root folder
#   - Used as a reliable reference point for configs, .env, and files
BASE_DIR = Path(__file__).resolve().parent.parent


# INPUT:
#   - () Operating system environment variables
#
# PROCESS:
#   - environ.Env() initializes the environment reader object
#   - This object is responsible for fetching values from the OS environment
#
# OUTPUT:
#   - `env` , stores the environment reader object
env = environ.Env()


# INPUT:
#   - Project root directory (BASE_DIR)
#   - .env file containing environment variables
#
# PROCESS:
#   - read_env() reads key-value pairs from the .env file
#   - Loads them into the OS environment for Django to access
#
# OUTPUT:
#   - Environment variables become available to settings.py via `env`
environ.Env.read_env(BASE_DIR / ".env")


# INPUT:
#   - Environment variable "DJANGO_DEBUG"
#
# PROCESS:
#   - env.bool() reads the value from the environment
#   - Converts it into a True / False boolean
#   - Defaults to False for safety if missing
#
# OUTPUT:
#   - DEBUG controls development vs production behavior
DEBUG = env.bool("DJANGO_DEBUG", default=False)



# INPUT:
#   - Environment variable "DJANGO_SECRET_KEY"
#
# PROCESS:
#   - env() fetches the value directly from the environment
#   - No default provided to force explicit configuration
#
# OUTPUT:
#   - SECRET_KEY secures sessions, tokens, and cryptographic signing
SECRET_KEY = env("DJANGO_SECRET_KEY")



# INPUT:
#   - Environment variable "DJANGO_ALLOWED_HOSTS"
#
# PROCESS:
#   - env.list() splits the comma-separated string into a Python list
#
# OUTPUT:
#   - ALLOWED_HOSTS defines which domains can access the app
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    # Local apps
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "docOps.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "docOps.wsgi.application"


# INPUT:
#   - Database connection variables from the environment
#
# PROCESS:
#   - env() reads each required value
#   - Django assembles them into a Postgres connection config
#
# OUTPUT:
#   - DATABASES config is fully environment-driven
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
